[409956] Auto build may throw java.lang.NoClassDefFoundError: org/eclipse/pde/core/plugin/PluginRegistry
Conflicts:
	plugins/org.eclipse.acceleo.common/src/org/eclipse/acceleo/common/AcceleoCommonPlugin.java